BloggersWorld/config/routes.rb
BloggersWorld::Application.routes.draw do
   
  devise_for :users

  match 'search' => 'blogs#search'
  
  resources :blogs do
      collection do
          get 'search'
      end
  end
  
  resources :blogs do
    resources :comments
  end
   
  
  

  
   
  
  
    
    

  root :to => 'home#index'
  
   

end

BloggersWorld/app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, :polymorphic => true
  attr_accessible :description, :image
  
  mount_uploader :image, ImageUploader
end

BloggersWorld/app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :Contents, :Name, :Title, :attachments_attributes
  
  has_many :comments, :dependent => :destroy
  has_many :attachments, :as => :attachable, :dependent => :destroy
  has_one :visit, :as => :visitable
  belongs_to :user
  
  accepts_nested_attributes_for :attachments
  # mount_uploader :image, ImageUploader
  
         
   
    def self.search(criteria='')
      criteria = "%#{criteria}%"         
          
      Blog.joins(:comments).where(["blogs.Name LIKE ? OR blogs.Contents LIKE ? OR comments.name LIKE ? OR comments.body LIKE ?", criteria, criteria,criteria, criteria])
      # Blog.joins("OUTER JOIN comments on coments.blog_id = blog.id").where(["blogs.Name LIKE ? OR blogs.Contents LIKE ? OR comments.name LIKE ? OR comments.body LIKE ?", criteria, criteria,criteria, criteria])
      
      # Blog.where(["Name LIKE ? OR Contents LIKE ?",criteria,criteria])  
      # UNION ALL 
      # Comment.where(["name LIKE ? OR body LIKE ?",criteria,criteria]))
      
       
      
      
      
      
   end
  validates :Name,  :presence => true
  validates :Title, :presence => true,
                    :length => { :minimum => 5 }

end

BloggersWorld/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
  attr_accessible :body, :name
  
  # def self.search(criteria='')
  #     criteria = "%#{criteria}%"
            
  #     Comment.where(["name LIKE ? OR body LIKE ?", criteria, criteria])
      
      
      
  #     # Blog.joins(:comments).where(["Name LIKE ? OR Contents LIKE ? OR name LIKE ? OR body LIKE ?", criteria, criteria,criteria, criteria])
  # end
  
  validates :name,  :presence => true
 
end

BloggersWorld/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :confirmable, :lockable, :timeoutable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :blogs, :dependent => :destroy
  # attr_accessible :title, :body
end

BloggersWorld/app/models/visit.rb
class Visit < ActiveRecord::Base
   
  
  belongs_to :visitable, :polymorphic => true
  has_many :visit_details, :dependent => :destroy
  
  def self.track(obj, ip_address)
    visit = Visit.find_or_create_by_visitable_id_and_visitable_type(obj.id, obj.class.name)
    ### check if visit is unique
    unless VisitDetail.find_by_visit_id_and_ip_address(visit.id, ip_address)
         visit.increment!(:unique_visits)
    end
    visit.increment!(:total_visits)
    visit_detail = visit.visit_details.create(:ip_address => ip_address)
  end
  
end

BloggersWorld/app/models/visit_detail.rb
class VisitDetail < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :ip_address
  belongs_to :visit
end

BloggersWorld/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  protected
  def authorize_user!
    if user_signed_in? && current_user.is_blogger
      return
    elsif user_signed_in?
      flash[:notice] = 'You must be an authorized blogger to do that'
      redirect_to :root
    else
      flash[:notice] = 'You need to sign in first'
      redirect_to new_user_session_path
    end
  end
  def ajax_no_layout
    if request.xhr?
      render :layout => false
    end
  end
  
end
  
  
  
  
  
  

BloggersWorld/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    
     
    before_filter :authorize_user!, :except => [:index, :show]
    
    def index
        
        @blogs = Blog.all
        ajax_no_layout
        
    end
    
    # def few_blogs
    #    @blogs = [Blog.first, Blog.last]
    #    render :index
    # end
    
    def show
        @blog = Blog.find(params[:id])
        # @comment = Comment.new( :blog => @blog )
        Visit.track(@blog, request.remote_ip)
        
    end
    
    def new
        @blog = Blog.new
        # @comments = Comment.all.map{|user| [user.name, user.id]}
    end
    
    def edit
        @blog = Blog.find(params[:id])
        # @comments = Comment.all.map{|user| [user.name, user.id]}
    end
    
    def create
        @blog = Blog.new(params[:blog])
        if @blog.save
            redirect_to @blog, notice: 'Blog was successfully created.'
        else
            render action: "new"
        end
    end
    
    def update
        @blog = Blog.find(params[:id])
        if @blog.update_attributes(params[:blog])
            redirect_to @blog, notice: 'Blog was successfully updated.'
        else
            render action: "edit"
        end
    end
    
    def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
        
        redirect_to blogs_url
    end
    
    def search
        
        @blogs = Blog.search(params[:q])
        # @comments = @blogs.comments
        # render action: "index"
    # if (@blogs.exists?) 
    #     render :partial => 'comments/comment', :content_type => 'text/html'
    # else
        render :partial => 'search_results', :content_type => 'text/html'
        
        
    # end
    
    end
    

end

BloggersWorld/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.create(params[:comment])
    redirect_to blog_path(@blog)
  end
  
  def destroy
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.find(params[:id])
    @comment.destroy
    redirect_to blog_path(@blog)
  end
  
   # def search
   #      @comments = Comment.search(params[:q])
   #      # render action: "index"
   #      render :partial => 'comments/comment', :content_type => 'text/html'
   #  end
    
end

BloggersWorld/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    
end

BloggersWorld/app/controllers/image_uploader.rb
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::RMagick

  storage :file

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  version :thumb do
    process :resize_to_limit => [200, 200]
  end
end

BloggersWorld/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver

        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
end

BloggersWorld/app/helpers/application_helper.rb
module ApplicationHelper
end

BloggersWorld/app/helpers/comments_helper.rb
module CommentsHelper
end

BloggersWorld/app/views/blogs/_form.html.haml
= form_for @blog, :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend
      Blog
    .control-group
      = f.label :Name, :class => 'control-label'
      .controls
        = f.text_field :Name, :class => 'text_field'
    
    .control-group
      = f.label :Title, :class => 'control-label'
      .controls
        = f.text_field :Title, :class => 'text_field'
    .control-group
      = f.label :Contents, :class => 'control-label'
      .controls
        = f.text_area :Contents, :class => 'text_field'
    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', blogs_path, :class => 'btn'
      

BloggersWorld/app/views/blogs/_newform.html.haml
= nested_form_for @blog, :html=>{:multipart => true } do |f|   
  %p
    = f.label :title
    %br/
    = f.text_field :Title
  %p
    = f.label :description
    %br/
    = f.text_area :Contents
  = f.fields_for :attachments do |attachment_form|
    %p
      = attachment_form.label :description
      %br/
      = attachment_form.text_area :description
    %p
      = attachment_form.label :image
      %br/
      = attachment_form.file_field :image
    = attachment_form.link_to_remove "Remove this attachment"
  = f.link_to_add "Add attachment", :attachments
  %p= f.submit

BloggersWorld/app/views/blogs/_photo_form.html.haml
= nested_form_for @blog, :html=>{:multipart => true } do |f|  
  = f.fields_for :attachments do |attachment_form|
    %p
      = attachment_form.label :description
      %br/
      = attachment_form.text_area :description
    %p
      = attachment_form.label :image
      %br/
      = attachment_form.file_field :image
    = attachment_form.link_to_remove "Remove this attachment"
  = f.link_to_add "Add attachment", :attachments
  %p= f.submit

BloggersWorld/app/views/blogs/_search_results.html.haml
%table
  %tr
  #search-results
    %td Name
    %td Title
    %td created_at 
  - @blogs.each do |blog|  
    %tr
      %td= blog.Name  
      %td= blog.Title  
      %td= blog.created_at
      %td 
        = link_to 'Show', blog_url(blog)
        = link_to 'Edit', edit_blog_url(blog)
        = link_to 'Delete', blog_url(blog), :method => :delete, :confirm => 'Are you sure?'
=link_to 'New', new_blog_url
         

BloggersWorld/app/views/blogs/edit.html.haml
// = render :partial => 'form'
// = render :partial => 'photo_form'
= render :partial => 'newform'

BloggersWorld/app/views/blogs/index.html.haml
.container
  %h2 
    List of Blogs     
 
  = render 'search_results'

BloggersWorld/app/views/blogs/new.html.haml
= render :partial => 'form'
= render :partial => 'photo_form'

BloggersWorld/app/views/blogs/show.html.haml
%h1 Blog Details
%p
  %b Name
  %br
  = @blog.Name
  %br
%p
  %b Title
  %br
    = @blog.Title
  %br
    
  %b Contents
  %br
    = @blog.Contents
  %br    
  %b Images
  %br
  %ul
    - for attachment in @blog.attachments
      %li      
        = image_tag( attachment.image_url)
    
    
%h2 Visits:
%p
  %span.gray Total:
  = @blog.visit.total_visits rescue 0
%p
  %span.gray Unique:
  = @blog.visit.unique_visits rescue 0
    
%h3 Comments
= render @blog.comments

    
%h3 Add a comment:
= render "comments/form"
%br/
.form-actions
  = link_to 'Back', blogs_path, :class => 'btn'
  = link_to 'Edit', edit_blog_path(@blog), :class => 'btn'
  = link_to 'Delete', blog_path(@blog), :method => 'delete', :confirm => 'Are you sure?'
  
 

BloggersWorld/app/views/comments/_comment.html.haml
%p
  %b Commenter:
  = comment.name
%p
  %b Comment:
  = comment.body
%p
  = link_to 'Destroy Comment', [comment.blog, comment], |
  :confirm => 'Are you sure?',                        |
  :method => :delete

BloggersWorld/app/views/comments/_form.html.haml
= form_for([@blog, @blog.comments.build]) do |f|
  .field
    = f.label :commenter
    %br/
    = f.text_field :name
  .field
    = f.label :body
    %br/
    = f.text_area :body
  .actions
    = f.submit  

BloggersWorld/app/views/home/index.html.haml
.hero-unit
  %p
    %b
      Hello Friends!

  %p
    Welcome to the 
    %i 
      %b Bloggers Tryst!
  %p
    This website is designed to encouraged users to share their thoughts on any topic they can think of! feel free to register for free and have fun!
  %p
    //  = button_to for post, link_to for get method
    
    = button_to "Get Started", { action: "index", :controller=>"/blogs"},form_class: "btn btn-large btn-success"

BloggersWorld/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Bloggers Tryst!
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body 
    .container
      %h1
        Welcome to the world of Bloggers!
      = render :partial => 'shared/nav'
      = render :partial => 'shared/session'
      = render :partial => 'shared/search'
      
      = yield
      %p
        %h3
          All rights reserved!

BloggersWorld/app/views/shared/_nav.html.haml
.navbar 
  .navbar-inner
    .container
      %ul.nav
        %li 
          = link_to 'Blogs Home',  root_path  
        %li
          = link_to 'Blog Index',blogs_path
        %li
          = link_to 'My Blogs',blogs_path
        %li
          = link_to 'Contact Us'
        

BloggersWorld/app/views/shared/_search.html.haml
.search
  = form_tag("/blogs/search", :method => "get" , :remote => true, 'search-result-target' => 'search-results') do
    = label_tag(:q, "Search for blogs:")
    = text_field_tag(:q)
    = submit_tag("Search")
// 
    
 

BloggersWorld/app/views/shared/_session.html.haml
#register
   
  - if user_signed_in?
    %p
      Hello #{current_user.email}
      %br/
      = link_to 'Sign out', destroy_user_session_path, :method => :delete
  - else
    %p
      = link_to 'Register', new_user_registration_path
      |
      \#{link_to 'Sign in', new_user_session_path}

BloggersWorld/app/views/users/index.html.haml
%table
  %tr
    %td email
    %td created_at 
  - @users.each do |user|  
    %tr
      %td= user.email        
      %td= user.created_at
      %td 
        // = link_to 'Show', blog_url(blog)
        // = link_to 'Edit', edit_blog_url(blog)
        // = link_to 'Delete', blog_url(blog), :method => :delete, :confirm => 'Are you sure?'
        // = render :partial => 'comment'
        